title: Nadun De Silva
tagline: An aspiring Software Engineer and ML Enthusiast
description: |
  Nadun De Silva is an aspiring Software Engineer and ML Enthusiast, interested in Machine Learning,
  Observability, Anomaly Detection & Cloud Technologies.
url: https://nadundesilva.github.io
author: Nadun De Silva
social:
  name: Nadun De Silva
  links:
    - https://www.facebook.com/nadunrds
    - https://www.linkedin.com/in/nadundesilva
    - https://www.instagram.com/nadunrds
    - https://github.com/nadundesilva
locale: en_US
logo: /assets/images/logo.png
twitter:
  username: nadunrds
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      seo:
        type: Person
      image:
        path: /assets/images/about/profile-photo.jpg
        height: 200
        width: 200
webmaster_verifications:
  yandex: acbc45e5d9645cf0
