title: Nadun De Silva
tagline: An aspiring Software Engineer and ML Enthusiast
description: |
  Personal website of Nadun De Silva who is an aspiring Software Engineer and Machine Learning Enthusiast.
url: https://nadundesilva.github.io
author: Nadun De Silva
social:
  name: Nadun De Silva
  links:
    - https://www.facebook.com/nadunrds
    - https://www.linkedin.com/in/nadundesilva
    - https://www.instagram.com/nadunrds
    - https://github.com/nadundesilva
locale: en_US
twitter:
  username: nadunrds
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
    values:
      seo:
        type: Person
      image:
        path: /assets/images/about/profile-photo.jpg
        height: 200
        width: 200
