- name: LinkedIn
  icon: fa fa-lg fa-linkedin
  link: https://www.linkedin.com/in/nadundesilva
- name: GitHub
  icon: fa fa-lg fa-github
  link: https://github.com/nadundesilva
- name: Medium
  icon: fa fa-lg fa-medium
  link: https://medium.com/@nadundesilva
- name: Facebook
  icon: fa fa-lg fa-facebook
  link: https://www.facebook.com/nadunrds
- name: Instagram
  icon: fa fa-lg fa-instagram
  link: https://www.instagram.com/nadunrds
- name: Twitter
  icon: fa fa-lg fa-twitter
  link: https://twitter.com/nadunrds
